teff=raw_input()
logg=raw_input()
met=raw_input()
vt=raw_input()
name=raw_input()
abon=open('abon2.dat', 'w')
abon.write(vt+'\n'+teff+' '+logg+' '+met+' 0.085 1\n')
abon.write('f 1 0 f  5 80\n\'raies_'+name+'.dat\' \'abon_'+name+'.dat\'\n')
abon.write('2\n FE1 FE2')
abon.close()
